---
- name: First Nginx Playbook
  hosts: foo
  
  tasks:
    - name: install Nginx from OS repos
      import_role:
        name: nginxinc.nginx
      vars:
        nginx_manage_repo: false
        nginx_install_from: os_repository
    - name: Create Custom Index Page
      import_role:
        name: nginxinc.nginx_config
      vars:
        nginx_config_html_demo_template_enable: true
        nginx_config_html_demo_template:
          - template_file: www/index.html.j2
            deployment_location: /var/www/html/index.html
            web_server_name: AHP NGINX Super Web Server
            backup: false
    - name: Create Custom Nginx configurations
      import_role:
        name: nginxinc.nginx_config
      vars:
        nginx_config_debug_output: true # temporary
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            deployment_location: /etc/nginx/sites-available/default
            backup: true
            config:
             servers:
               - core:
                   listen:
                     - port: 80
                   server_name: _
                 log:
                   access:
                     - path: /var/log/nginx/default_server.log
                 locations:
                   - location: /
                     core:
                       index: index.html index.htm index.nginx-debian.html
                       root: /var/www/html


